ci: rectified syntax error and incorrect code block for file check

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -52,10 +52,9 @@ jobs:
       # Check required git cliff files present in repo
       - name: Check required git cliff files in repo
         run: |
-          if [[ ! -z "$USER_INPUT_VERSION" ]] ; then
-            echo "Type of release:"$USER_INPUT_VERSION" from user ${GITHUB_ACTOR}"
-          else
-            echo "User did not select release type. It will be automatically determined..."
+          if [[ ! -f cliff.toml || ! -f cliff-changelog.toml ]]; then
+            echo "Error: Both cliff.toml and cliff-changelog.toml files must be present in repo root"
+            exit 1
           fi
 
       # Install yarn dependencies (git-cliff)
@@ -66,11 +65,11 @@ jobs:
         env:
           USER_INPUT_VERSION: "${{ github.event.inputs.input_version }}"
         run: |
-          if [[ ! -z "$USER_INPUT_VERSION"]]; then;
+          if [[ ! -z "$USER_INPUT_VERSION" ]] ; then
             echo "Type of release:"$USER_INPUT_VERSION" from user ${GITHUB_ACTOR}"
           else
-            echo "User did not select release type. Will be automatically determined..."
-
+            echo "User did not select release type. It will be automatically determined..."
+          fi
       # Get the latest tag info, increment it accordingly, update the package.json file so it is built with new version
       - name: Update version info for build
         id: version
@@ -175,7 +174,7 @@ jobs:
       - name: Publish to npm
         run: yarn npm publish --provenance
 
-      - name: Create Signed Tag via GH CLI and fetch tags
+      - name: Create Signed Tag via GH CLI and fetch new tag
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
           TAG_NAME: ${{ needs.bump-version.outputs.new-tag }}
@@ -193,7 +192,7 @@ jobs:
           GH_TOKEN: ${{ github.token }}
           TAG_NAME: ${{ needs.bump-version.outputs.new-tag }}
         run: |
-          gh release edit "$TAG_NAME" --notes-file "${{ runner.temp }}/RELEASE_NOTES.md" --draft=false --latest
+          gh release edit "$TAG_NAME" --notes-file "${{ runner.temp }}/RELEASE_NOTES.md" --latest
 
       - name: Attest
         uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
